site_name: AI/ML Programmers Handbook
site_author: Tudor Morariu
site_url: https://MorariuT.github.io/AI_Docs/

repo_name: MorariuT/MorariuT.github.io
repo_url: https://github.com/MorariuT/MorariuT.github.io
edit_uri: edit/main/AI_Docs/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Documentation:
      - Basics:
          - Matrix Algebra: Basics/matrix.md 
          - Statistics Basics: Basics/Statistics.md
          - Cost/Loss Functions: Basics/CostFunctions.md
          - Gradient Descent: Basics/GradientDescent.md
      - Linear Models: 
          - Linear Regression: linear_models/LinearRegression.md
          - Logistic Regression: linear_models/LogisticRegression.md
      - Neural Networks:
          - Basics: NeuralNetworks/Basics.md
          - Forward Propagation: NeuralNetworks/ForwardPropagation.md
          - Back Propagation: NeuralNetworks/BackPropagation.md
          - Simple Neural Network: NeuralNetworks/SimpleNeuralNetwork.md
      - Computer Vision:
          - Basics: ComputerVision/Basics.md
          - Convolution: ComputerVision/Convolution.md
          - CNN: ComputerVision/CNN.md
          - Data Processing: ComputerVision/DataProcessing.md
      - Natural Language Processing:
          - Basics: NLP/Basics.md
          - Simple Embedders: NLP/SimpleEmbedders.md
          - Attention: NLP/Attention.md
          - Transformers: NLP/Transformers.md
      - Ensemble Models:
          - Decision Trees: ensemble_models/DecisionTree.md
          - Random Forests: ensemble_models/RandomForests.md
          - Boosting: ensemble_models/Boosting.md
          - Voting Models: ensemble_models/VotingModels.md
      - Data Analysis:
          - Introduction: DataAnalisys/Intro.md
          - PCA: DataAnalisys/PCA.md
          - LDA: DataAnalisys/LDA.md
          - UMAP: DataAnalisys/UMap.md
          - Statistics: DataAnalisys/Statistics.md
          - Useful Plots: DataAnalisys/UsefullPlots.md

